name: Release
on: [push]

jobs:

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GITHUB_REF: $GITHUB_REF"

      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=version::0.0.4

      - name: Checkout code
        uses: actions/checkout@v3

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: "0.0.4"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  release-ubuntu:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install dgctl
          pip install pyinstaller
          pyinstaller src/dgctl/dgctl.py
          cd dist/dgctl
          zip -r dgctl.zip dgctl

      - name: upload ubuntu artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dgctl.zip
          asset_name: dgctl-linux.zip
          asset_content_type: application/gzip

  release-macos:
    needs: create-release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install dgctl
          pip install pyinstaller
          pyinstaller src/dgctl/dgctl.py
          ./dist/dgctl/dgctl

  release-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          python3 -m venv .venv
          .venv\Scripts\activate
          pip install dgctl
          pip install pyinstaller
          pyinstaller src\dgctl\dgctl.py
          dist\dgctl\dgctl
