name: Release Linux
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          ls ${{ github.workspace }}
